/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/TicTacToeTileScript")]
    [LuaRegisterType(0x19cebb229977cd9c, typeof(LuaBehaviour))]
    public class TicTacToeTileScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "b37b50d6dff7d1e479f98d6bbdaf7646";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_X = default;
        [SerializeField] public UnityEngine.GameObject m_O = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_X),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_O),
            };
        }
    }
}

#endif
