/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CheckpointScript")]
    [LuaRegisterType(0x781256d1bffba048, typeof(LuaBehaviour))]
    public class CheckpointScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "37ab51a5960820b44884752524a1f619";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_Stage = 0;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Stage),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/CheckpointScript/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
