/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/FallTrapScript")]
    [LuaRegisterType(0x9278fb606715514, typeof(LuaBehaviour))]
    public class FallTrapScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "3604872782363cf449f7adf832028419";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_TrapBox = default;
        [SerializeField] public UnityEngine.GameObject m_SafeBox = default;
        [SerializeField] public System.Double m_offsetTimer = 0;
        [SerializeField] public System.Double m_intervalTimer = 2;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_TrapBox),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_SafeBox),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_offsetTimer),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_intervalTimer),
            };
        }
    }
}

#endif
