/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/FinishZoneScript")]
    [LuaRegisterType(0x45174d7b45c629b7, typeof(LuaBehaviour))]
    public class FinishZoneScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "bdedbffa123cb6d458982765f2e91ca3";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.ParticleSystem m_winParticle = default;
        [SerializeField] public Highrise.AudioShader m_winSound = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_winParticle),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_winSound),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/FinishZoneScript/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
