/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ObstacleHud")]
    [LuaRegisterType(0x222ee7fe4fb60225, typeof(LuaBehaviour))]
    public class ObstacleHud : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "d96ece193066c844f92ab9870d4f8825";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_checkpointCount = 0;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_checkpointCount),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
            };
        }
    }
}

#endif
