/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PlayerTracker")]
    [LuaRegisterType(0xda26101afdd629bc, typeof(LuaBehaviour))]
    public class PlayerTracker : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "ceec1f725587a584591266998d05e6e6";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public Highrise.AudioShader m_checkpointSound = default;
        [SerializeField] public UnityEngine.Transform m_ChackPoint1 = default;
        [SerializeField] public UnityEngine.Transform m_ChackPoint2 = default;
        [SerializeField] public UnityEngine.Transform m_ChackPoint3 = default;
        [SerializeField] public UnityEngine.Transform m_ChackPoint4 = default;
        [SerializeField] public UnityEngine.Transform m_ChackPoint5 = default;
        [SerializeField] public UnityEngine.Transform m_ChackPoint6 = default;
        [SerializeField] public UnityEngine.Transform m_ChackPoint7 = default;
        [SerializeField] public UnityEngine.Transform m_ChackPoint8 = default;
        [SerializeField] public UnityEngine.Transform m_ChackPoint9 = default;
        [SerializeField] public UnityEngine.Transform m_ChackPoint10 = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_checkpointSound),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_ChackPoint1),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_ChackPoint2),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_ChackPoint3),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_ChackPoint4),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_ChackPoint5),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_ChackPoint6),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_ChackPoint7),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_ChackPoint8),
                CreateSerializedProperty(_script.GetPropertyAt(9), m_ChackPoint9),
                CreateSerializedProperty(_script.GetPropertyAt(10), m_ChackPoint10),
            };
        }
    }
}

#endif
