/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/RadioScript")]
    [LuaRegisterType(0xcae628cb8e66fc4f, typeof(LuaBehaviour))]
    public class RadioScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "dbd55daaf8c8d0b41b2ef0aaf144a1a5";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_URL = "";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_URL),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/RadioScript/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
