/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/TapObject")]
    [LuaRegisterType(0x3f94dbf6e377bd19, typeof(LuaBehaviour))]
    public class TapObject : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "24619e3059718de438e49efdff263124";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public Highrise.AudioShader _vibrateTap = default;
        [SerializeField] public Highrise.AudioShader _tapSound = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _vibrateTap),
                CreateSerializedProperty(_script.GetPropertyAt(1), _tapSound),
            };
        }
    }
}

#endif
