/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CameraTriggerScript")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class CameraTriggerScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "6c1b4cdcd5fd8db4d9e2cac2527c2fe5";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_myShopIndicator = default;
        [SerializeField] public UnityEngine.GameObject m_Cam = default;
        [SerializeField] public UnityEngine.LayerMask m_MainMaskVis = default;
        [SerializeField] public UnityEngine.LayerMask m_MainMaskClick = default;
        [SerializeField] public UnityEngine.LayerMask m_MyMask = default;
        [SerializeField] public System.String m_myLayerName = "Default";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_myShopIndicator),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_Cam),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_MainMaskVis),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_MainMaskClick),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_MyMask),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_myLayerName),
            };
        }
    }
}

#endif
