/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ColorPeg")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class ColorPeg : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "8122741e05b374843b890a1fa87cfed4";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_pegB = default;
        [SerializeField] public UnityEngine.GameObject m_pegG = default;
        [SerializeField] public UnityEngine.GameObject m_pegO = default;
        [SerializeField] public UnityEngine.GameObject m_pegP = default;
        [SerializeField] public UnityEngine.GameObject m_pegR = default;
        [SerializeField] public UnityEngine.GameObject m_pegV = default;
        [SerializeField] public UnityEngine.GameObject m_pegW = default;
        [SerializeField] public UnityEngine.GameObject m_pegY = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_pegB),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_pegG),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_pegO),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_pegP),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_pegR),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_pegV),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_pegW),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_pegY),
            };
        }
    }
}

#endif
