/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ColorPicker")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class ColorPicker : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "2408f21dee4578741a039c15f121a7be";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_Color = "o";
        [SerializeField] public UnityEngine.GameObject m_Spawner = default;
        [SerializeField] public UnityEngine.Animator m_anim = default;
        [SerializeField] public System.Boolean m_hasAnim = true;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Color),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_Spawner),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_anim),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_hasAnim),
            };
        }
    }
}

#endif
