/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/EscalatorBlocker")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class EscalatorBlocker : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "fff975c6b554b674a8a1bc38d44b6354";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Transform m_Top = default;
        [SerializeField] public UnityEngine.Transform m_Bottom = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Top),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_Bottom),
            };
        }
    }
}

#endif
