/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/EscalatorScript")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class EscalatorScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "37f0c07f642264547bb3ad31ca4f323e";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_Escalator = default;
        [SerializeField] public System.Boolean m_Forward = true;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Escalator),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_Forward),
            };
        }
    }
}

#endif
