/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/FireWorksScript")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class FireWorksScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "e01aed9458955734da1f9e01d27b09e1";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_FireWorks = default;
        [SerializeField] public UnityEngine.GameObject m_Button = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_FireWorks),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_Button),
            };
        }
    }
}

#endif
