/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/InteractScript")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class InteractScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "5d523b9150177834bbcfcb2a5e6cad33";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Boolean m_HasAnimation = false;
        [SerializeField] public System.Boolean m_HasAudio = false;
        [SerializeField] public System.Boolean m_HasParticle = false;
        [SerializeField] public UnityEngine.GameObject m_particle = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_HasAnimation),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_HasAudio),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_HasParticle),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_particle),
            };
        }
    }
}

#endif
