/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/LightBoardSpawner")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class LightBoardSpawner : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "07cbbd908bfed524586b00a4c0e911f9";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_prefabToSpawn = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_prefabToSpawn),
            };
        }
    }
}

#endif
