/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PigeonScript")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class PigeonScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "5bd5e45281b700644869b3e8d7f2449d";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_Poop = default;
        [SerializeField] public UnityEngine.GameObject m_FlyDirTransform = default;
        [SerializeField] public System.Boolean m_RandomizeRot = true;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Poop),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_FlyDirTransform),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_RandomizeRot),
            };
        }
    }
}

#endif
