/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PigeonSpawner")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class PigeonSpawner : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "c39fa84fb5816114f9404f84930cbb05";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_Pigeon = default;
        [SerializeField] public UnityEngine.Vector2 m_birdCount = new Vector2(0, 0);
        [SerializeField] public UnityEngine.Vector2 m_birdBannerCount = new Vector2(0, 0);
        [SerializeField] public System.Double m_spawnRadius = 1.35;
        [SerializeField] public UnityEngine.GameObject m_BannerEP1 = default;
        [SerializeField] public UnityEngine.GameObject m_BannerEP2 = default;
        [SerializeField] public UnityEngine.GameObject m_BannerEP3 = default;
        [SerializeField] public UnityEngine.GameObject m_BannerEP4 = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Pigeon),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_birdCount),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_birdBannerCount),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_spawnRadius),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_BannerEP1),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_BannerEP2),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_BannerEP3),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_BannerEP4),
            };
        }
    }
}

#endif
