/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PuddleScript")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class PuddleScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "4671e34617c66304e861ec56105a348c";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.ParticleSystem m_particle = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_particle),
            };
        }
    }
}

#endif
