/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/SodaFountain")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class SodaFountain : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "364224af9ad6b4444b01c7ee76b7170b";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_Particle1 = default;
        [SerializeField] public UnityEngine.GameObject m_Particle2 = default;
        [SerializeField] public UnityEngine.GameObject m_Particle3 = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Particle1),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_Particle2),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_Particle3),
            };
        }
    }
}

#endif
