/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/HangManController")]
    [LuaRegisterType(0xfec24b044c61d767, typeof(LuaBehaviour))]
    public class HangManController : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "6e5270b1870de824492fa4823774bd1c";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_hangMan = default;
        [SerializeField] public UnityEngine.GameObject m_worldUIObj = default;
        [SerializeField] public Highrise.AudioShader m_newClip = default;
        [SerializeField] public Highrise.AudioShader m_wrongClip = default;
        [SerializeField] public Highrise.AudioShader m_savedClip = default;
        [SerializeField] public Highrise.AudioShader m_deadClip = default;
        [SerializeField] public Highrise.AudioShader m_weeheeClip = default;
        [SerializeField] public Highrise.AudioShader m_rightClip = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_hangMan),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_worldUIObj),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_newClip),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_wrongClip),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_savedClip),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_deadClip),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_weeheeClip),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_rightClip),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/HangManController/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
