/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/TaskScript")]
    [LuaRegisterType(0x76182a206bf8a697, typeof(LuaBehaviour))]
    public class TaskScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "17a3dcbb72f444844849e2d2f59df9c6";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_taskName = "";
        [SerializeField] public System.Double m_taskRole = 1;
        [SerializeField] public System.Boolean m_proximityTask = false;
        [SerializeField] public System.Double m_taskXPReq = 0;
        [SerializeField] public System.Double m_taskXPReward = 0;
        [SerializeField] public System.Double m_taskCashReward = 0;
        [SerializeField] public System.Double m_tasktime = 0;
        [SerializeField] public System.Double m_taskCooldowntime = 0;
        [SerializeField] public UnityEngine.GameObject m_uiObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_taskName),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_taskRole),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_proximityTask),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_taskXPReq),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_taskXPReward),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_taskCashReward),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_tasktime),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_taskCooldowntime),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_uiObject),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/TaskScript/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
