/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

using System;
using System.Linq;
using UnityEngine;
using UnityEditor;

namespace Highrise.Studio.Generated
{
    internal static class LuaMenuItems
    {
        private static Type s_luaScriptType;
        private static Type s_luaBehaviourType;

        private static void LoadScriptType()
        {
            var assembly = AppDomain.CurrentDomain.GetAssemblies().FirstOrDefault(a => a.GetName().Name == "com.pz.highrise.lua");
            if (assembly == null)
                return;

            s_luaScriptType = assembly.GetTypes().FirstOrDefault(t => t.Name == "LuaScript");
            if (s_luaScriptType == null)
                return;

            assembly = AppDomain.CurrentDomain.GetAssemblies().FirstOrDefault(a => a.GetName().Name == "com.pz.highrise.game.client");
            if (assembly == null)
                return;

            s_luaBehaviourType = assembly.GetTypes().FirstOrDefault(t => t.Name == "LuaBehaviour");
            if (s_luaBehaviourType == null)
                return;
        }

        private static void AddScript(string path)
        {
            var gameObjects = Selection.gameObjects;
            if (gameObjects.Length == 0)
                return;

            if (s_luaScriptType == null)
                LoadScriptType();

            if (s_luaScriptType == null || s_luaBehaviourType == null)
                return;

            var asset = AssetDatabase.LoadAssetAtPath(path, s_luaScriptType);
            if (asset == null)
                return;

            AddScript(gameObjects, asset);
        }

        private static void AddScript(GameObject[] parents, UnityEngine.Object script)
        {
            Undo.SetCurrentGroupName("Add Lua");

            foreach(var parent in parents)
            {
                var so = new SerializedObject(Undo.AddComponent(parent, s_luaBehaviourType));
                so.FindProperty("_script").objectReferenceValue = script;
                so.ApplyModifiedProperties();
            }

            Undo.RecordObjects(parents, "Add Lua");
        }

        [MenuItem("Component/Lua/Legacy Charactr Size Script")]
        private static void AddComponent1() => AddScript("Assets/Template/LegacyCharactrSizeScript.lua");
        [MenuItem("Component/Lua/Add R Bto Player")]
        private static void AddComponent2() => AddScript("Assets/Template/Scripts/AddRBtoPlayer.lua");
        [MenuItem("Component/Lua/Bio Scanner")]
        private static void AddComponent3() => AddScript("Assets/Template/Scripts/BioScanner.lua");
        [MenuItem("Component/Lua/CCTV Script")]
        private static void AddComponent4() => AddScript("Assets/Template/Scripts/CCTVScript.lua");
        [MenuItem("Component/Lua/Chat Manager")]
        private static void AddComponent5() => AddScript("Assets/Template/Scripts/ChatManager.lua");
        [MenuItem("Component/Lua/Corpse Script")]
        private static void AddComponent6() => AddScript("Assets/Template/Scripts/CorpseScript.lua");
        [MenuItem("Component/Lua/Door Script")]
        private static void AddComponent7() => AddScript("Assets/Template/Scripts/DoorScript.lua");
        [MenuItem("Component/Lua/Key Pad Mixer")]
        private static void AddComponent8() => AddScript("Assets/Template/Scripts/KeyPadMixer.lua");
        [MenuItem("Component/Lua/Key Pad Toggle")]
        private static void AddComponent9() => AddScript("Assets/Template/Scripts/KeyPadToggle.lua");
        [MenuItem("Component/Lua/Kill Box Script")]
        private static void AddComponent10() => AddScript("Assets/Template/Scripts/KillBoxScript.lua");
        [MenuItem("Component/Lua/Meeting Button Script")]
        private static void AddComponent11() => AddScript("Assets/Template/Scripts/MeetingButtonScript.lua");
        [MenuItem("Component/Lua/My RTS Cam")]
        private static void AddComponent12() => AddScript("Assets/Template/Scripts/MyRTSCam.lua");
        [MenuItem("Component/Lua/Player Manager")]
        private static void AddComponent13() => AddScript("Assets/Template/Scripts/PlayerManager.lua");
        [MenuItem("Component/Lua/Radio Script")]
        private static void AddComponent14() => AddScript("Assets/Template/Scripts/RadioScript.lua");
        [MenuItem("Component/Lua/Ready Button")]
        private static void AddComponent15() => AddScript("Assets/Template/Scripts/ReadyButton.lua");
        [MenuItem("Component/Lua/Task Master")]
        private static void AddComponent16() => AddScript("Assets/Template/Scripts/TaskMaster.lua");
        [MenuItem("Component/Lua/Tutorial Pop Up Script")]
        private static void AddComponent17() => AddScript("Assets/Template/Scripts/TutorialPopUpScript.lua");
        [MenuItem("Component/Lua/Vent Script")]
        private static void AddComponent18() => AddScript("Assets/Template/Scripts/VentScript.lua");
        [MenuItem("Component/Lua/Vote Box Script")]
        private static void AddComponent19() => AddScript("Assets/Template/Scripts/VoteBoxScript.lua");
        [MenuItem("Component/Lua/Anchor Old")]
        private static void AddComponent20() => AddScript("Packages/com.pz.studio/Runtime/Lua/AnchorOld.lua");
        [MenuItem("Component/Lua/General Chat")]
        private static void AddComponent21() => AddScript("Packages/com.pz.studio/Runtime/Lua/GeneralChat.lua");
        [MenuItem("Component/Lua/Highrise Camera Controller")]
        private static void AddComponent22() => AddScript("Packages/com.pz.studio/Runtime/Lua/HighriseCameraController.lua");
        [MenuItem("Component/Lua/RTS Camera")]
        private static void AddComponent23() => AddScript("Packages/com.pz.studio/Runtime/Lua/RTSCamera.lua");
        [MenuItem("Component/Lua/Scene Loader")]
        private static void AddComponent24() => AddScript("Packages/com.pz.studio/Runtime/Lua/SceneLoader.lua");

    }
}

