/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ThirdPersonCamera")]
    [LuaRegisterType(0xfda764a7cdaf1f04, typeof(LuaBehaviour))]
    public class ThirdPersonCamera : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "28961782db12e774c850c8f79f628237";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_cameraPivotHeight = 2.5;
        [SerializeField] public System.Double m_initalDistanceFromPivot = 7.5;
        [SerializeField] public System.Double m_minDistanceFromPivot = 3;
        [SerializeField] public System.Double m_maxDistanceFromPivot = 25;
        [SerializeField] public UnityEngine.Vector3 m_cameraOffset = new Vector3(0.75f, 0.5f, 0f);
        [SerializeField] public System.Boolean m_EnableMaxPitch = true;
        [SerializeField] public System.Boolean m_EnableMaxYaw = false;
        [SerializeField] public System.Double m_initialPitch = 10;
        [SerializeField] public System.Double m_minPitch = -5;
        [SerializeField] public System.Double m_maxPitch = 30;
        [SerializeField] public System.Double m_minYaw = -360;
        [SerializeField] public System.Double m_maxYaw = 360;
        [SerializeField] public System.Double m_touchRotationSensitivity = 0.4;
        [SerializeField] public System.Double m_mouseRotationSensitivity = 0.4;
        [SerializeField] public System.Double m_rotationSmoothing = 1;
        [SerializeField] public System.Double m_touchZoomSensitivity = 5;
        [SerializeField] public System.Double m_FOV = 60;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_cameraPivotHeight),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_initalDistanceFromPivot),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_minDistanceFromPivot),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_maxDistanceFromPivot),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_cameraOffset),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_EnableMaxPitch),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_EnableMaxYaw),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_initialPitch),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_minPitch),
                CreateSerializedProperty(_script.GetPropertyAt(9), m_maxPitch),
                CreateSerializedProperty(_script.GetPropertyAt(10), m_minYaw),
                CreateSerializedProperty(_script.GetPropertyAt(11), m_maxYaw),
                CreateSerializedProperty(_script.GetPropertyAt(12), m_touchRotationSensitivity),
                CreateSerializedProperty(_script.GetPropertyAt(13), m_mouseRotationSensitivity),
                CreateSerializedProperty(_script.GetPropertyAt(14), m_rotationSmoothing),
                CreateSerializedProperty(_script.GetPropertyAt(15), m_touchZoomSensitivity),
                CreateSerializedProperty(_script.GetPropertyAt(16), m_FOV),
            };
        }
    }
}

#endif
