/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CharacterCollisionScript")]
    [LuaRegisterType(0xcd776a7b0b4b117b, typeof(LuaBehaviour))]
    public class CharacterCollisionScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "647a8636e1f50e641bc8243306848983";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.AudioClip m_playerLostClip = default;
        [SerializeField] public UnityEngine.AudioClip m_playerWonClip = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_playerLostClip),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_playerWonClip),
            };
        }
    }
}

#endif
