/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/EnergyOrbScript")]
    [LuaRegisterType(0xc9a3328fda4b38c9, typeof(LuaBehaviour))]
    public class EnergyOrbScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "23a57df8ac847734fb7db29f7a1dc36d";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Boolean m_Timed = false;
        [SerializeField] public System.Boolean m_Lightning = false;
        [SerializeField] public UnityEngine.AudioClip m_Clip = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Timed),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_Lightning),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_Clip),
            };
        }
    }
}

#endif
