/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/EnergySpawner")]
    [LuaRegisterType(0xbcdd18b569a96abf, typeof(LuaBehaviour))]
    public class EnergySpawner : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "9ca502029beda1e41b57ff26ecdde4f0";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_energyOrb = default;
        [SerializeField] public UnityEngine.GameObject m_lightningPickup = default;
        [SerializeField] public System.Double m_maxAmount = 10;
        [SerializeField] public System.Double m_minAmount = 5;
        [SerializeField] public System.Double m_spawnDistance = 15;
        [SerializeField] public System.Double m_lightningChance = 10;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_energyOrb),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_lightningPickup),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_maxAmount),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_minAmount),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_spawnDistance),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_lightningChance),
            };
        }
    }
}

#endif
