/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/LifeTimeScript")]
    [LuaRegisterType(0x14b78f54633b075d, typeof(LuaBehaviour))]
    public class LifeTimeScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "87508c667ff3fa842a7a84eb6d863820";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_lifeTime = 5;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_lifeTime),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/LifeTimeScript/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
