/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PlayerManager")]
    [LuaRegisterType(0xfe9baceb5f86083f, typeof(LuaBehaviour))]
    public class PlayerManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "d726fd71545e0394888efe1edc69697f";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_EnergyOrb = default;
        [SerializeField] public UnityEngine.GameObject m_LightningEffect = default;
        [SerializeField] public UnityEngine.GameObject m_Camera = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_EnergyOrb),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_LightningEffect),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_Camera),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/PlayerManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
